spring:
    application:
        name: CareMate-Backend

    datasource:
        url: jdbc:mysql://localhost:3306/caremate?serverTimezone=Asia/Seoul
        username: root
        password: 1234

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        defer-datasource-initialization: true
    sql.init.mode: always

    mail:
        host: smtp.gmail.com
        port: 587
        username: hayunseo14@gmail.com
        password: ravbdlsvqlyrabwg
        properties:
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true
            mail.smtp.ssl.trust: smtp.gmail.com
            mail.debug: true

    jwt:
        secret: TrmFK2Nox5h5JtGd6IoNcuSdVCg5dX9cr8LsE7Cm+k3notiNNkSVJU8GLQ9B33I/mBwayz0MiAwdVHW6Xa/FBw==

    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true

    management:
        endpoints:
            web:
                exposure:
                    include: health,info
        endpoint:
            health:
                show-details: always
        server:
            port: ${PORT:8080}
